# TFIDF L2

# -------------------------------------------------------

In [1]:
import pandas as pd
import numpy as np
from scipy.linalg import norm
import seaborn as sns
import plotly_express as px
sns.set()
import configparser
config = configparser.ConfigParser()
config.read("../../../env.ini")

[]

In [2]:
sns.set(style='ticks')

In [3]:
OHCO = ['artist', 'song','lines', 'token_num']
colors = 'YlGnBu'

In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

# -------------------------------------------------------

## Import CORPUS

In [43]:
LIB = pd.read_csv('lib.csv').set_index(OHCO[:1])
CORPUS = pd.read_csv('tokens.csv').set_index(OHCO)
VOCAB = pd.read_csv('vocab.csv').set_index('term_str')
DTM = pd.read_csv('DTM.csv').set_index(['artist', 'song'])
BOW = pd.read_csv('bow_by_artists.csv').set_index('term_str')

In [44]:
VOCAB

,n,p,i,n_chars,max_pos_group,max_pos,stop,porter_stem,df,idf,dfidf
term_str,,,,,,,,,,,
NaN,12014,0.128561,2.959478,0,",",",",0,NaN,NaN,NaN,NaN
i,4849,0.051889,4.268436,1,PR,PRP,1,i,10.0,0.137504,1.375035
you,3962,0.042397,4.559894,3,PR,PRP,1,you,10.0,0.137504,1.375035
the,2130,0.022793,5.455269,3,DT,DT,1,the,11.0,0.000000,0.000000
it,2056,0.022001,5.506282,2,PR,PRP,1,it,8.0,0.459432,3.675453
...,...,...,...,...,...,...,...,...,...,...,...
duffel,1,0.000011,16.511907,6,NN,NN,0,duffel,1.0,3.459432,3.459432
couple,1,0.000011,16.511907,6,NN,NN,0,coupl,1.0,3.459432,3.459432
housekeeping,1,0.000011,16.511907,12,NN,NNP,0,housekeep,1.0,3.459432,3.459432
bells,1,0.000011,16.511907,5,NN,NNS,0,bell,1.0,3.459432,3.459432
possible,1,0.000011,16.511907,8,JJ,JJ,0,possibl,1.0,3.459432,3.459432

In [45]:
BOW

                   artist    n        tf     tfidf
term_str
92cause             ADELE    1  0.000060  0.000149
a                   ADELE  187  0.011307  0.001555
able                ADELE    1  0.000060  0.000113
about               ADELE   11  0.000665  0.000434
above               ADELE    4  0.000242  0.000275
...                   ...  ...       ...       ...
yours     WHITNEY HOUSTON    6  0.000334  0.000379
yourself  WHITNEY HOUSTON    3  0.000167  0.000190
yuletide  WHITNEY HOUSTON    1  0.000056  0.000192
z         WHITNEY HOUSTON    2  0.000111  0.000385
zone      WHITNEY HOUSTON    1  0.000056  0.000192

[8218 rows x 4 columns]

In [48]:
TFIDF = pd.read_csv('tfidf.csv').set_index('artist')
TFIDF

,1,10,130,14,16,180,2,20,2020,213,...,yourself,youu8197,youu8287,youuc0u8197,youuc0u8287,yuh,yuletide,z,zion,zone
artist,,,,,,,,,,,,,,,,,,,,,
ADELE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
AMY WINEHOUSE,0.000000,0.000000,0.000000,0.000318,0.000000,0.000318,0.000000,0.000000,0.000000,0.000000,...,0.001671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ARIANA GRANDE,0.000000,0.000000,0.000224,0.000000,0.000000,0.000000,0.000000,0.000000,0.000224,0.000000,...,0.000221,0.000000,0.000000,0.000000,0.000000,0.006049,0.000000,0.000000,0.000000,0.000000
BEYONCE,0.000000,0.000000,0.000000,0.000000,0.032032,0.000000,0.034712,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
CYNDI LAUPER,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013989,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
DOLLY PARTON,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
DUA LIPA,0.026446,0.000000,0.000000,0.000000,0.000000,0.000000,0.020156,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LAURYN HILL,0.018084,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025437,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025437,0.000000
PINK,0.000000,0.003341,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TAYLOR SWIFT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000127,0.000387,0.000387,0.000387,0.000387,0.000000,0.000000,0.000000,0.000000,0.000000
WHITNEY HOUSTON,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000192,...,0.000190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000192,0.000385,0.000000,0.000192

In [49]:
pos_set = ['NN', 'VB']
VSHORT = VOCAB[VOCAB.max_pos_group.isin(['NN', 'VB', 'JJ']) & ~VOCAB.max_pos.isin(['NNP'])].sort_values('dfidf', ascending=False).head(5000)
TFIDF = TFIDF[VSHORT.index]

In [50]:
TFIDF

,taken,drama,goodbye,understand,wants,going,tired,rest,tall,glass,...,compasses,grind,possible,thing,mind,good,night,want,is,love
artist,,,,,,,,,,,,,,,,,,,,,
ADELE,0.000088,0.000000,0.000265,0.000529,0.000794,0.000000,0.000618,0.000088,0.001147,0.000000,...,0.000000,0.000000,0.000000,0.000315,0.000525,0.000193,0.000228,0.001085,0.001873,0.0
AMY WINEHOUSE,0.000134,0.000268,0.001206,0.001474,0.000000,0.000536,0.000804,0.000134,0.000402,0.000134,...,0.000000,0.000000,0.000000,0.000213,0.000292,0.000319,0.000532,0.000399,0.002153,0.0
ARIANA GRANDE,0.000000,0.000095,0.000000,0.000000,0.000000,0.000095,0.000284,0.000189,0.000000,0.000095,...,0.000000,0.000000,0.000000,0.000206,0.000450,0.000600,0.000337,0.001200,0.001575,0.0
BEYONCE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.002681,0.000000,0.000000,0.002681,0.000000,0.000000,0.0
CYNDI LAUPER,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008642,0.006481,0.002160,0.0
DOLLY PARTON,0.000000,0.000000,0.000000,0.000000,0.010576,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.002098,0.002098,0.000000,0.000000,0.006294,0.0
DUA LIPA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.003113,0.003113,0.006226,0.003113,0.006226,0.003113,0.0
LAURYN HILL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.002129,0.004257,0.002129,0.000000,0.002129,0.002129,0.0
PINK,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000705,...,0.000000,0.000000,0.000000,0.000559,0.000280,0.000280,0.000559,0.000419,0.000000,0.0
TAYLOR SWIFT,0.000082,0.000245,0.000082,0.000082,0.000571,0.000082,0.000245,0.000245,0.000163,0.000326,...,0.000193,0.000193,0.000000,0.000421,0.000146,0.000194,0.000485,0.000938,0.002475,0.0
WHITNEY HOUSTON,0.000081,0.000081,0.000487,0.000081,0.000162,0.001055,0.000000,0.000000,0.000081,0.000000,...,0.000000,0.000000,0.000192,0.000161,0.000290,0.000612,0.000708,0.000595,0.002333,0.0

# -------------------------------------------------------

## Normalizing - L2 form

In [51]:
TFIDF_L2 = (TFIDF.T / norm(TFIDF, 2, axis=1)).T

In [52]:
TFIDF_L2

,taken,drama,goodbye,understand,wants,going,tired,rest,tall,glass,...,compasses,grind,possible,thing,mind,good,night,want,is,love
artist,,,,,,,,,,,,,,,,,,,,,
ADELE,0.002641,0.000000,0.007923,0.015847,0.023770,0.000000,0.018488,0.002641,0.034335,0.000000,...,0.000000,0.000000,0.000000,0.009431,0.015718,0.005763,0.006811,0.032483,0.056059,0.0
AMY WINEHOUSE,0.004011,0.008023,0.036103,0.044126,0.000000,0.016046,0.024069,0.004011,0.012034,0.004011,...,0.000000,0.000000,0.000000,0.006366,0.008753,0.009549,0.015915,0.011936,0.064456,0.0
ARIANA GRANDE,0.000000,0.002529,0.000000,0.000000,0.000000,0.002529,0.007588,0.005059,0.000000,0.002529,...,0.000000,0.000000,0.000000,0.005519,0.012042,0.016057,0.009032,0.032113,0.042149,0.0
BEYONCE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.019555,0.000000,0.000000,0.019555,0.000000,0.000000,0.0
CYNDI LAUPER,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.085762,0.064322,0.021441,0.0
DOLLY PARTON,0.000000,0.000000,0.000000,0.000000,0.128549,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.025500,0.025500,0.000000,0.000000,0.076500,0.0
DUA LIPA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.021621,0.021621,0.043241,0.021621,0.043241,0.021621,0.0
LAURYN HILL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.017200,0.034399,0.017200,0.000000,0.017200,0.017200,0.0
PINK,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012578,...,0.000000,0.000000,0.000000,0.009980,0.004990,0.004990,0.009980,0.007485,0.000000,0.0
TAYLOR SWIFT,0.002702,0.008105,0.002702,0.002702,0.018912,0.002702,0.008105,0.008105,0.005403,0.010807,...,0.006404,0.006404,0.000000,0.013934,0.004823,0.006431,0.016078,0.031085,0.081999,0.0
WHITNEY HOUSTON,0.002336,0.002336,0.014016,0.002336,0.004672,0.030369,0.000000,0.000000,0.002336,0.000000,...,0.000000,0.000000,0.005537,0.004634,0.008341,0.017609,0.020390,0.017146,0.067193,0.0

In [53]:
csv_file = 'tfidf_l2.csv'
TFIDF_L2.to_csv(csv_file)

# -------------------------------------------------------